### ISSUE TITLE
journal.enabled to false on arbiters?

### ISSUE THREAD

**Issue by MrMMorris** [appelgriebsch/dockers#2]
Hi!

Thanks so much for creating this. Makes setting up a replica set so easy. Got 2 member + 1 arbiter working on ec2, all separate hosts :+1:

One thing I wanted to ask: **is there a reason why journal is not disabled for arbiters?** I'm a bit of a mongo noob so I just thought I'd ask as that is what the docs recommend.

If it makes sense to have it disabled, I can easily submit a PR :grinning:

**Comment by appelgriebsch** [comment]
Sorry, just haven't had the time to care about the details in the last weeks and months. If you want to contribute feel free to create a pull request. Have just updated the repo and introduced Mongo-3.0 support. Doesn't have looked at all the new things and how to update the scripts to support them though.

**Comment by MrMMorris** [comment]
PR: https://github.com/appelgriebsch/dockers/pull/3
